version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --save 60 1
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - redis
    restart: unless-stopped

  redis-datasource:
    image: redis/redis-stack:latest
    ports:
      - "8001:8001"
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data:
    name: proxy_redis_data
    driver: local
  grafana_data:
    name: proxy_grafana_data
    driver: local 